server:
  port: 8080

spring:
  datasource:
    # Persistent SQL database for now (data survives app restart)
    url: jdbc:h2:./plantosdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=MYSQL
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

